test: bitshift.c
	gcc -o test.out bitshift.c
	clear
	./test.out

test2: bitshift2.c
	gcc -o test2.out bitshift2.c
	clear
	./test2.out

all:
	make test
	make test2
	clear
	./test.out
	./test2.out
clean:
	rm *.out

